feat(ci): streamline artifact preparation and update README formatting

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -32,15 +32,11 @@ jobs:
       - name: Prepare Artifacts
         run: |
           mkdir -p artifacts/osx artifacts/windows artifacts/linux
-          cp cli/target/buildcli.jar artifacts/osx/
-          cp cli/target/buildcli.jar artifacts/windows/
-          cp cli/target/buildcli.jar artifacts/linux/
-          cp scripts/osx/buildcli artifacts/osx/
-          cp scripts/windows/buildcli.bat artifacts/windows/
-          cp scripts/linux/buildcli artifacts/linux/
+          cp cli/target/buildcli.jar artifacts/
+          cp -r scripts/* artifacts/
 
       - name: Upload Artifacts
-        uses:  actions/upload-artifact@v4
+        uses: actions/upload-artifact@v4
         with:
           name: buildcli-artifacts
           path: artifacts/
@@ -71,6 +67,7 @@ jobs:
       - name: Verify BuildCLI installation on Ubuntu
         if: matrix.os == 'ubuntu-latest'
         run: |
+          cp artifacts/buildcli.jar artifacts/linux/
           chmod +x artifacts/linux/buildcli
           if ! ./artifacts/linux/buildcli version; then
             echo "BuildCLI command not found or failed to execute."
@@ -80,16 +77,18 @@ jobs:
       - name: Verify BuildCLI installation on macOS
         if: matrix.os == 'macos-latest'
         run: |
+          cp artifacts/buildcli.jar artifacts/osx/
           chmod +x artifacts/osx/buildcli
           if ! ./artifacts/osx/buildcli version; then
-            echo "BuildCLI command not found or failed to execute."
-            exit 1
+          echo "BuildCLI command not found or failed to execute."
+          exit 1
           fi
 
       - name: Verify BuildCLI installation on Windows
         if: matrix.os == 'windows-latest'
         run: |
+          cp artifacts\buildcli.jar artifacts\windows\
           if (-not (artifacts\windows\buildcli.bat version)) {
-            Write-Error "BuildCLI command not found or failed to execute."
-            exit 1
+          Write-Error "BuildCLI command not found or failed to execute."
+          exit 1
           }
